### PR TITLE
Add AspectJWeaver file write gadget

### PR DESCRIPTION
**Pull request by testanull**
Add AspectJWeaver file write gadget
Gadget chain:
HashSet.readObject()
    HashMap.put()
        HashMap.hash()
            TiedMapEntry.hashCode()
                TiedMapEntry.getValue()
                    LazyMap.get()
                        SimpleCache$StorableCachingMap.put()
                            SimpleCache$StorableCachingMap.writeToPath()
                                FileOutputStream.write()

### CODE REVIEW

**Comment by frohoff** [comment]
Can you try using `@PayloadTest(harness="ysoserial.test.payloads.FileUploadTest")` to see if it can pass the test?

**Comment by testanull** [comment]
I have tried to remove the comons-io deps
But the errors come from the original FileUpload1, not from mine
image

**Comment by testanull** [comment]
My bad, I didn't know about recent changes in the deps
Just updated it

**Comment by testanull** [comment]
Hey, any update yet?

**Comment by frohoff** [comment]
Was able to get it to work after the merge with master. Thanks for the PR!

**Pull request merged**
