### PR TITLE
Vaadingadget

### PR DESCRIPTION
**Pull request by supersache**
New Gadget for WebUI Framework Vaadin, version 7.7.14. Tested with Oracle JRE 8u151.

### CODE REVIEW

**Comment by frohoff** [comment]
Tests appear to be failing. Looks like it probably needs to be annotated with version checks similar to `CommonsCollections5` and a few others that use JDK gadgets that have changed.

https://github.com/frohoff/ysoserial/blob/477ecb8f05f42b0195a67d9712e97f2c6d31e1da/src/main/java/ysoserial/payloads/CommonsCollections5.java

```java
@PayloadTest (precondition = "isApplicableJavaVersion")
...
    public static boolean isApplicableJavaVersion() {
        return JavaVersion.isBadAttrValExcReadObj();
    }
```

**Comment by supersache** [comment]
Looks like also reference to vaadin-shared was missing. Regarding the remaining checks that fail I cannot see whether the failures have sth to do with the gadget or if yes what.

**Comment by frohoff** [comment]
The other failures look to be caused by other gadgets that will probably need similar JDK version checks due to recent changes. 

I'll merge this after you get an acknowledgement from the vaadin dev team.

**Comment by frohoff** [comment]
Cleaned up a bunch of test-related issues on `master` branch that allows tests to pass cleanly on this PR now.

**Pull request merged**
