### PR TITLE
MozillaRhino2 gadget

### PR DESCRIPTION
**Pull request by tint0**
Another chain for Mozilla Rhino with a couple of improvements over the last one.

- Rhino 1.6R7 has an internal bug that will break the rhino1 chain, this still works
- Doesn't rely on BadAttributeValueExpException
- Much smaller object size

### CODE REVIEW

**Comment by frohoff** [comment]
Looks good. If you notify the rhino devs and get an acknowledgement from them I'll go ahead and merge.

**Comment by tint0** [comment]
Will this do? mozilla/rhino#520

**Comment by frohoff** [comment]
That works, thanks. Merged.

**Comment by tint0** [comment]
Thanks!

**Pull request merged**
